name: voyager-v2

services:
  mongo:
    image: mongo:6
    container_name: voyager-mongo-v2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: voyager-redis-v2
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: voyager-backend-v2
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    dn:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - mongo
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./backend:/app
      - /app/node_modules

  ml-worker:
    build:
      context: ./backend
      dockerfile: worker.Dockerfile
    container_name: voyager-ml-worker-v2
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - ml
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: ${MONGO_URI}

  ml:
    build:
      context: ./ml
    container_name: voyager-ml-api-v2
    restart: always
    ports:
      - "5050:5000"
    env_file:
      - ./ml/.env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY} 
    volumes:
      - ./ml:/app

volumes:
  mongo_data:
