name: Voyager CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job 1: Lint and test backend
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    defaults:
      run:
        working-directory: ./backend
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && echo "✅ MongoDB is up" && break
            echo "⏳ Waiting for MongoDB..." && sleep 3
          done

      - name: Run linter (optional)
        run: npm run lint || echo "No linter configured"

      - name: Run tests
        run: npm test

  # Job 2: Build & push Docker images
  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend API image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-backend:latest

      - name: Build and push ML Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/worker.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-ml-worker:latest

      - name: Build and push ML API image
        uses: docker/build-push-action@v5
        with:
          context: ./ml
          file: ./ml/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-ml:latest

  # Job 3: Deploy to EC2
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save EC2 key to file
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Test SSH connectivity
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo ✅ Connected successfully"

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Voyager
            git pull origin main
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker compose pull
            docker compose down
            docker compose up -d --build
