name: Voyager CI/CD

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job 1: Run tests and linters to ensure code quality
  lint-and-test:
    name: "Lint & Test Backend"
    runs-on: ubuntu-latest
    
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7 
        ports:
          - 6379:6379
          
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Wait for services to be ready
        run: |
          echo "⏳ Waiting for services..."
          # Use a tool like 'nc' (netcat) to check if ports are open
          # This is more reliable than a simple sleep
          for i in {1..10}; do
            if nc -z localhost 27017 && nc -z localhost 6379; then
              echo "✅ MongoDB and Redis are up!"
              break
            fi
            echo "Attempt $i: Services not ready yet, sleeping 3s..."
            sleep 3
          done

      - name: Run linter (optional)
        run: npm run lint || echo "No linter configured"

      - name: Run tests with CI environment variables
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_HOST: localhost 
          REDIS_PORT: 6379

  # Job 2: Build all service images and push to Docker Hub
  build-and-push:
    name: "Build & Push Docker Images"
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Backend API image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-backend:latest

      - name: Build and push ML Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/worker.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-ml-worker:latest
          
      - name: Build and push ML API image
        uses: docker/build-push-action@v5
        with:
          context: ./ml
          file: ./ml/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voyager-ml:latest

  # Job 3: Deploy to the EC2 staging server
  # in .github/workflows/ci.yml

  deploy-to-staging:
    name: "Deploy to Staging (EC2)"
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Voyager
            
            # Discard any local changes to tracked files
            echo "Discarding any local changes on the server..."
            git reset --hard HEAD
            
            echo "Pulling the latest version from GitHub..."
            git pull origin main
            
            # Log in to Docker Hub
            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # Use the production compose file to pull and restart services
            echo "Pulling latest Docker images..."
            docker compose -f docker-compose.yaml pull
            
            echo "Restarting services with new images..."
            docker compose -f docker--compose.yaml up -d --force-recreate